baseURL = ""

publishDir = "docs"

languageCode = "en-us"

title = "Arenas"

enableRobotsTXT = true

pluralizelisttitles = false

disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
	description = "Website about Cuban writer Reinaldo Arenas"
	images = ["/reinaldo-arenas.jpg"]
	title = "Arenas"
